import Dependencies._
import org.scalafmt.sbt.ScalafmtPlugin.autoImport.scalafmtOnCompile
import sbt.Keys.{semanticdbEnabled, semanticdbVersion, versionScheme}
import sbt.VirtualAxis.ScalaVersionAxis

lazy val supportedScalaVersions = List(scalaVersion213, scalaVersion212)

ThisBuild / scalaVersion := supportedScalaVersions.head
ThisBuild / organization := "org.virtuslab"
ThisBuild / organizationName := "VirtusLab"
ThisBuild / versionScheme := Some("early-semver")
ThisBuild / homepage := Some(url("https://github.com/VirtusLab/akka-serialization-helper"))
ThisBuild / licenses := List(
  "MIT License" -> url("https://github.com/VirtusLab/akka-serialization-helper/blob/main/LICENSE"))
ThisBuild / developers := List(
  Developer("MarconZet", "Marcin Złakowski", "mzlakowski@virtuslab.com", url("https://github.com/MarconZet")),
  Developer("HubertBalcerzak", "Hubert Balcerzak", "hubertbalc@gmail.com", url("https://github.com/HubertBalcerzak")),
  Developer("PawelLipski", "Paweł Lipski", "plipski@virtuslab.com", url("https://github.com/PawelLipski")))

Global / onChangedBuildSource := ReloadOnSourceChanges

ThisBuild / semanticdbEnabled := true
ThisBuild / semanticdbVersion := scalafixSemanticdb.revision
ThisBuild / scalafixDependencies += "com.github.liancheng" %% "organize-imports" % "0.5.0"

lazy val commonSettings = Seq(
  scalafmtOnCompile := true,
  scalacOptions ++= Seq(
      "-deprecation",
      "-encoding",
      "UTF-8",
      "-feature",
      "-language:_",
      "-Xlog-reflective-calls",
      "-Xlint:_",
      "-Ybackend-parallelism",
      "8",
      "-Ywarn-dead-code",
      "-Ywarn-unused",
      "-unchecked",
      if (sys.env.getOrElse("CI", "false") == "true") "-Xfatal-warnings" else ""),
  libraryDependencies ++= commonDeps)

publish / skip := true

lazy val scalaVersionAxis = settingKey[Option[String]]("Project scala version")

lazy val circeAkkaSerializer = (projectMatrix in file("circe-akka-serializer"))
  .settings(name := "circe-akka-serializer")
  .settings(commonSettings)
  .settings(
    libraryDependencies ++= Seq(
        akkaTyped % Provided,
        akkaTestKit % Test,
        akkaStream % Provided,
        circeCore,
        circeParser,
        circeGeneric,
        circeGenericExtras,
        reflections,
        scalaCollectionCompat),
    scalaVersionAxis := {
      virtualAxes.value.collectFirst { case x: ScalaVersionAxis => x.value }
    })
  .settings(
    resolvers += Resolver.sonatypeRepo("releases"),
    libraryDependencies ++=
      scalaVersionAxis.value.map {
        case "2.13" => Seq(scalaReflect % scalaVersion213)
        case "2.12" =>
          Seq(
            scalaReflect % scalaVersion212,
            compilerPlugin(("org.scalamacros" % "paradise" % "2.1.1" % Test).cross(CrossVersion.full))
          ) // Add macro annotations to scala 2.12
      }.get,
    Test / scalacOptions ++= scalaVersionAxis.value.map {
        case "2.13" =>
          Seq(
            "-Ymacro-annotations", // Semiautomatic circe codec derivation uses macro annotations.
            "-Xlint:-byname-implicit" // Not disabling byname-implicit raises warnings on code generated by Circe macros
          )
        case "2.12" => Seq.empty
      }.get)
  .jvmPlatform(scalaVersions = supportedScalaVersions)

lazy val ashAnnotation = (projectMatrix in file("ash-annotation"))
  .settings(name := "ash-annotation")
  .settings(commonSettings)
  .jvmPlatform(scalaVersions = supportedScalaVersions)

lazy val serializabilityCheckerCompilerPlugin = (projectMatrix in file("serializability-checker-compiler-plugin"))
  .settings(name := "serializability-checker-compiler-plugin")
  .settings(commonSettings)
  .settings(
    libraryDependencies ++= {
      virtualAxes.value
        .collectFirst { case x: ScalaVersionAxis => x.value }
        .map {
          case "2.13" => scalaPluginDeps213
          case "2.12" => scalaPluginDeps212
        }
        .getOrElse(Seq.empty)
    },
    libraryDependencies ++= Seq(akkaTyped % Test, akkaPersistence % Test, akkaProjections % Test, betterFiles % Test))
  .dependsOn(ashAnnotation)
  .jvmPlatform(scalaVersions = supportedScalaVersions)

lazy val codecRegistrationCheckerCompilerPlugin = (projectMatrix in file("codec-registration-checker-compiler-plugin"))
  .settings(name := "codec-registration-checker-compiler-plugin")
  .settings(commonSettings)
  .settings(
    libraryDependencies ++= {
      virtualAxes.value
        .collectFirst { case x: ScalaVersionAxis => x.value }
        .map {
          case "2.13" => scalaPluginDeps213
          case "2.12" => scalaPluginDeps212
        }
        .getOrElse(Seq.empty)
    },
    libraryDependencies ++= Seq(betterFiles % Test))
  .dependsOn(ashAnnotation)
  .jvmPlatform(scalaVersions = supportedScalaVersions)

lazy val sbtAkkaSerializationHelper = (project in file("sbt-akka-serialization-helper"))
  .enablePlugins(SbtPlugin)
  .settings(name := "sbt-akka-serialization-helper")
  .settings(commonSettings)
  .settings(
    pluginCrossBuild / sbtVersion := "1.2.8",
    scalaVersion := scalaVersion212,
    libraryDependencies ++= Seq(sprayJson, circeCore, circeGeneric, circeYaml, betterFiles),
    scriptedLaunchOpts := {
      scriptedLaunchOpts.value ++
      Seq(
        "-Xmx1024M",
        "-Dplugin.version=" + version.value,
        "-Dcompiler-plugin.version=" + (dumpPersistenceSchemaCompilerPlugin.componentProjects.head / version).value)
    },
    scriptedDependencies := { // publishing compiler plugin locally for testing
      scriptedDependencies.value
      // this can't be abstracted to function because of the limitation of sbt macro expansion
      (dumpPersistenceSchemaCompilerPlugin.projectRefs.head / publishLocal).value
      (dumpPersistenceSchemaCompilerPlugin.projectRefs.tail.head / publishLocal).value // both head and tail.head must be published because they are separate projects, one for scala 2.13, one for 2.12
      (codecRegistrationCheckerCompilerPlugin.projectRefs.head / publishLocal).value
      (codecRegistrationCheckerCompilerPlugin.projectRefs.tail.head / publishLocal).value
      (serializabilityCheckerCompilerPlugin.projectRefs.head / publishLocal).value
      (serializabilityCheckerCompilerPlugin.projectRefs.tail.head / publishLocal).value
      (ashAnnotation.projectRefs.head / publishLocal).value
      (ashAnnotation.projectRefs.tail.head / publishLocal).value
    },
    scriptedBufferLog := false)

lazy val dumpPersistenceSchemaCompilerPlugin = (projectMatrix in file("dump-persistence-schema-compiler-plugin"))
  .enablePlugins(AssemblyPlugin)
  .settings(name := "dump-persistence-schema-compiler-plugin")
  .settings(commonSettings)
  .settings(
    libraryDependencies ++= {
      virtualAxes.value
        .collectFirst { case x: ScalaVersionAxis => x.value }
        .map {
          case "2.13" => scalaPluginDeps213
          case "2.12" => scalaPluginDeps212
        }
        .getOrElse(Seq.empty)
    },
    libraryDependencies ++= Seq(sprayJson, betterFiles, akkaTyped % Test, akkaPersistence % Test),
    packageBin / publishArtifact := false, //we want to publish fat jar
    Compile / packageBin / artifactPath := crossTarget.value / "packageBinPlaceholder.jar", //this ensures that normal jar doesn't override fat jar
    assembly / assemblyMergeStrategy := {
      case PathList(
            "scala",
            "annotation",
            "nowarn.class" | "nowarn$.class"
          ) => //scala-collection-compat duplicates no-warn.class, as it was added to scala 2.12 after its release
        MergeStrategy.first
      case x =>
        (assembly / assemblyMergeStrategy).value.apply(x)
    },
    Compile / assembly / artifact := {
      val art = (Compile / assembly / artifact).value
      art.withClassifier(None)
    },
    assembly / assemblyJarName := s"${name.value}_${scalaBinaryVersion.value}-${version.value}.jar", //Warning: this is a default name for packageBin artefact. Without explicit rename of packageBin will result in race condition
    addArtifact(Compile / assembly / artifact, assembly))
  .jvmPlatform(scalaVersions = supportedScalaVersions)
