#!/bin/sh

# This can be symlinked from .git/hooks/pre-commit in the repo with:
# ln -s ../../pre-commit .git/hooks/pre-commit
# Make sure the file is executable.

sbt scalafmtAll scalafixAll scalafmtSbt

cd examples/event-migration
sbt scalafmtAll scalafixAll scalafmtSbt

cd ../akka-cluster-app
sbt scalafmtAll scalafixAll scalafmtSbt

cd ../akka-persistence-app
sbt scalafmtAll scalafixAll scalafmtSbt
