#!/usr/bin/env bash

this_file=$0
# Find todos in comments NOT followed by an issue number
# (?!...) is negative lookahead, requires Perl syntax
if git grep --perl-regexp -I --ignore-case --line-number '(\*|//|#|<!--).*(todo)(?! \(#[0-9]+\):)' -- ":(exclude)$this_file"; then
  echo
  echo "Use 'TODO (#<issue-number>): <short-description>' format for the above TODOs"
  exit 1
fi
