#!/bin/sh

set -e -x

sbt scalafmtAll scalafixAll scalafmtSbt

cd examples/event-migration
sbt scalafmtAll scalafixAll scalafmtSbt

cd ../akka-cluster-app
sbt scalafmtAll scalafixAll scalafmtSbt

cd ../akka-persistence-app
sbt scalafmtAll scalafixAll scalafmtSbt
