#!/bin/sh

set -e -x

sbt scalafmtAll scalafixAll scalafmtSbt

cd examples/event-migration
sbt scalafmtAll scalafixAll scalafmtSbt

cd ../pekko-cluster-app
sbt scalafmtAll scalafixAll scalafmtSbt

cd ../pekko-persistence-app
sbt scalafmtAll scalafixAll scalafmtSbt
