#!/usr/bin/env bash

set -e -o pipefail -u

sbt publishLocal

version=$(ls -1t ~/.ivy2/local/org.virtuslab.psh/sbt-pekko-serialization-helper/scala_2.12/sbt_1.0/ | head -1)
# Version can be more elegantly extracted using:
#   sbt -Dsbt.supershell=false -error "print sbtPekkoSerializationHelper/version"
# but the problem is that snapshot versions include minute-resolution timestamp,
# which is likely to change from the preceding `sbt publishLocal`.

find . -type f | grep '\.sbt$' | xargs sed -E 's/("sbt-pekko-serialization-helper") % ".*"/\1 % "'"$version"'"/' -i
