#!/usr/bin/env bash

set -e -o pipefail -u

self_dir=$(cd "$(dirname "$0")" &>/dev/null; pwd -P)
source "$self_dir"/utils.sh

case ${GITHUB_REF-} in
  # We don't want a main branch/tag build to fail because some linked website has a random downtime.
  refs/heads/main) extra_options='' ;;
  refs/tags/*) extra_options='' ;;
  *) extra_options='--use=lint-no-dead-urls' ;;
esac

remark --use=validate-links $extra_options --ignore-path=.gitignore --frail .
