name: Publish GitHub Release

on:
  push:
    tags:
      - 'v*'

jobs:
  run-scala-ci-release:
    uses: ./.github/workflows/standard-workflow.yml
    secrets: inherit

  publish-maven-artifacts:
    needs: [run-scala-ci-release]
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: coursier/cache-action@v7
      - uses: sbt/setup-sbt@v1

      - run: git fetch --tags
      - name: Publish Maven artifacts
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

  publish-github-release:
    needs: [run-scala-ci-release]
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      # Publishes new Release as new git tag (vX.Y.Z) is pushed to repository
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: publish-release-config.yml
          publish: true
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
